import type { Metadata } from "next";
import Link from "next/link";

import { LegalList, LegalPage, LegalSection } from "@/components/legal";

export const metadata: Metadata = {
  title: "Terms of Service — PickWise",
  description:
    "The terms that apply when you use PickWise's laptop recommendations, PickScore, and Pico chat.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="16 July 2026"
      intro="These terms apply whenever you use PickWise. By creating an account or using the service, you agree to them. If you don't agree, please don't use PickWise."
    >
      <LegalSection title="1. What PickWise is">
        <p>
          PickWise is a laptop recommendation and price-comparison service for
          the Malaysian market. It combines a product catalog, our{" "}
          <strong>PickScore</strong> rating methodology, and{" "}
          <strong>Pico</strong>, an AI chat assistant, to help you shortlist
          laptops that fit your needs, budget, and preferences. PickWise is an
          information service only — we do not sell laptops, process payments,
          or fulfil orders.
        </p>
      </LegalSection>

      <LegalSection title="2. Your account">
        <LegalList
          items={[
            <>
              You can register with a username, email, and password, or sign in
              with Google. Registration requires verifying your email address
              before you can log in.
            </>,
            <>
              Keep your credentials secure. You are responsible for activity
              that happens under your account.
            </>,
            <>
              Provide accurate information, and keep it up to date via your
              profile page.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection title="3. Acceptable use">
        <p>PickWise is for personal, non-commercial use. You agree not to:</p>
        <LegalList
          items={[
            "Scrape, bulk-download, or republish our catalog, scores, or content by automated means.",
            "Probe, disrupt, or attempt to gain unauthorized access to the service or other users' accounts.",
            "Abuse Pico — for example, attempting to make it perform tasks unrelated to laptop shopping, or using it to generate harmful content.",
            "Misrepresent PickWise content as coming from the manufacturers or retailers it describes.",
          ]}
        />
      </LegalSection>

      <LegalSection title="4. AI-generated content">
        <p>
          Pico&apos;s replies and explanations are generated by AI and{" "}
          <strong>can be wrong, incomplete, or out of date</strong>. PickScore
          is our own scoring methodology built from public benchmark data and
          product specifications — it is an opinion expressed as a number, not
          a guarantee of real-world performance. Always verify specifications,
          compatibility, and prices with the manufacturer or retailer before
          buying. Nothing on PickWise is professional or financial advice.
        </p>
      </LegalSection>

      <LegalSection title="5. Prices and product information">
        <LegalList
          items={[
            <>
              All prices are shown in <strong>Malaysian Ringgit (RM)</strong>{" "}
              and are collected from manufacturers&apos; websites and public
              sources. They can lag behind, differ from what a retailer
              charges, or contain errors.
            </>,
            <>
              Any purchase happens between you and a third-party retailer.
              PickWise is not a party to that transaction and is not
              responsible for retailer stock, delivery, warranty, or after-sales
              service.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection title="6. Intellectual property">
        <p>
          The PickWise service — including PickScore, Pico, and our design and
          content — belongs to us. Laptop names, product images, logos, and
          trademarks belong to their respective owners; their appearance on
          PickWise does not imply any affiliation with or endorsement by those
          companies.
        </p>
      </LegalSection>

      <LegalSection title="7. Availability and changes">
        <p>
          PickWise is provided free of charge and we may add, change, suspend,
          or remove features at any time. We aim to keep the service available
          but do not guarantee uninterrupted operation.
        </p>
      </LegalSection>

      <LegalSection title="8. Suspension and termination">
        <p>
          We may suspend or close accounts that violate these terms or abuse
          the service. You can stop using PickWise at any time and may request
          deletion of your account and data (see the{" "}
          <Link
            href="/privacy"
            className="text-brand underline underline-offset-2"
          >
            Privacy Policy
          </Link>
          ).
        </p>
      </LegalSection>

      <LegalSection title="9. Disclaimers and limitation of liability">
        <p>
          PickWise is provided <strong>&ldquo;as is&rdquo;</strong> without
          warranties of any kind. To the maximum extent permitted by law, we
          are not liable for indirect or consequential losses, or for purchase
          decisions made based on recommendations, scores, or prices shown on
          PickWise.
        </p>
      </LegalSection>

      <LegalSection title="10. Governing law">
        <p>These terms are governed by the laws of Malaysia.</p>
      </LegalSection>

      <LegalSection title="11. Changes to these terms">
        <p>
          We may update these terms from time to time. We&apos;ll change the
          &ldquo;Last updated&rdquo; date above when we do; continuing to use
          PickWise after an update means you accept the revised terms.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
